"""Aggregate the one-shot system evaluation without changing frozen rules."""
import collections,json
from pathlib import Path
import numpy as np
ROOT=Path(__file__).parents[1]
load=lambda n:json.loads((ROOT/n).read_text())
def dump(n,x):(ROOT/n).write_text(json.dumps(x,indent=2,ensure_ascii=False)+'\n')
d=load('SYSTEM_SEALED_RESULTS_V1.json');rows=d['rows'];plan=load('SYSTEM_SEALED_EXTRACTION_PLAN_V1.json');names={r['action']:r['action_name'] for r in plan['observations']}
pose={'a000084':'SUPPORT_QUADRUPED','a001422':'SEATED','a000017':'PRONE_LIKE_SUPPORT','a001199':'CROUCH_FORWARD_LEAN','a005386':'HORIZONTAL_SUPINE_TWIST','a001415':'SEATED_KNEEL','a001444':'HORIZONTAL_SIDE','a001135':'KNEEL_FORWARD','a000219':'HORIZONTAL_GLUTE_BRIDGE','a000681':'CROUCH_KNEEL'}
views={'a000084':'BACK_VISIBLE_OBLIQUE','a001422':'BACK_VISIBLE','a000017':'BACK_VISIBLE_OBLIQUE','a001199':'BACK_PARTIAL_OVERHEAD','a005386':'FRONT_SIDE_OBLIQUE','a001415':'BACK_VISIBLE','a001444':'SIDE_VISIBLE','a001135':'BACK_VISIBLE_OBLIQUE','a000219':'FRONT_SIDE_OBLIQUE','a000681':'BACK_VISIBLE_OVERHEAD'}
systems=['O','A','G_exact','G_gpu','B','C']
def group(field):
 out={}
 for value in sorted(set(field(r) for r in rows)):
  rr=[r for r in rows if field(r)==value];out[value]={'frames':len(rr),'descriptive_only':len(rr)<6,'absolute_mm':{s:float(np.mean([x['systems'][s]['median_mm'] for x in rr])) for s in systems},'p95_mm':{s:float(np.mean([x['systems'][s]['p95_mm'] for x in rr])) for s in systems}}
 return out
matrix={'status':'DESCRIPTIVE_MULTI_POSE_AUDIT','source_of_pose':'action metadata verified against RGB contact sheets','actions':{a:{'action_name':names[a],'pose_family':pose[a],'view_family':views[a],'frames':sum(r['action']==a for r in rows)} for a in sorted(names)},'per_pose_family':group(lambda r:pose[r['action']]),'per_view_family':group(lambda r:views[r['action']]),'claim_limit':'Small cells are descriptive; no universal pose support claim.'};dump('SUPPORTED_POSE_RESEARCH_MATRIX_V1.json',matrix)
subject={}
for sid in sorted(set(r['subject_id'] for r in rows)):
 rr=[r for r in rows if r['subject_id']==sid];subject[sid]={s:float(np.median([x['systems'][s]['median_mm'] for x in rr])) for s in systems};subject[sid]['winner']=min(systems,key=lambda s:subject[sid][s])
low=[r for r in rows if r['systems']['O']['median_mm']<30];high=[r for r in rows if r['systems']['O']['median_mm']>=60]
comparison={'status':'ONE_SHOT_SYSTEM_SEALED_COMPLETE','subjects':4,'actions':12,'frames':36,'subject_equal':d['systems'],'per_subject':subject,'low_official_under_30mm':{'frames':len(low),'regressed':{s:sum(r['systems'][s]['median_mm']>r['systems']['O']['median_mm'] for r in low) for s in systems}},'high_official_at_least_60mm':{'frames':len(high),'improved':{s:sum(r['systems'][s]['median_mm']<r['systems']['O']['median_mm'] for r in high) for s in systems}},'correction_out_of_range_fallback_frames':sum(r['correction_out_of_range'] for r in rows),'exact_gpu_agreement':d['choices']['exact_gpu_agreement']};dump('SYSTEM_COMPARISON_V1.json',comparison)
rt=d['runtime'];cost={'status':'MEASURED_2080TI','p50_ms':{'Official_only':rt['official_p50_ms'],'Adapted_second_forward':rt['adapted_second_p50_ms'],'G_exact_model_forwards':rt['official_p50_ms']+rt['adapted_second_p50_ms'],'G_gpu_total':rt['official_p50_ms']+rt['adapted_second_p50_ms']+rt['gpu_residual_p50_ms'],'C_total':rt['official_p50_ms']+rt['cheap_correction_p50_ms'],'gpu_residual':rt['gpu_residual_p50_ms'],'cheap_correction':rt['cheap_correction_p50_ms']},'peak_vram_mb':rt['peak_vram_mb'],'relative_to_official':{'G_gpu_extra_ms':rt['adapted_second_p50_ms']+rt['gpu_residual_p50_ms'],'C_extra_ms':rt['cheap_correction_p50_ms'],'G_gpu_absolute_gain_mm':d['systems']['O']['median_mm']['mean_of_subject_frame_medians']-d['systems']['G_gpu']['median_mm']['mean_of_subject_frame_medians'],'C_absolute_gain_mm':d['systems']['O']['median_mm']['mean_of_subject_frame_medians']-d['systems']['C']['median_mm']['mean_of_subject_frame_medians']},'scope':'Forward/correction/residual timers exclude dataset decode and Camera-B evaluation.'};dump('SYSTEM_RUNTIME_COST_V1.json',cost)
final={'status':'BOTH_USEFUL_DIFFERENT_TRADEOFFS','abstention_status':'ABSOLUTE_FAILURE_DETECTION_NOT_READY','primary_result':{'O_mm':d['systems']['O']['median_mm']['mean_of_subject_frame_medians'],'G_exact_mm':d['systems']['G_exact']['median_mm']['mean_of_subject_frame_medians'],'G_gpu_mm':d['systems']['G_gpu']['median_mm']['mean_of_subject_frame_medians'],'C_mm':d['systems']['C']['median_mm']['mean_of_subject_frame_medians']},'decision':'C has the best central error, three-of-four subject behavior, and lower latency. G_gpu has slightly better P95 and rescues a subject where C is weaker. Use C as the engineering default candidate and retain G_gpu as a high-robustness candidate until product-domain data decides.','not_claimed':['arbitrary pose robustness','treatment-table or bare-back performance','back-region accuracy','DMD37/acupoint accuracy','clinical safety'],'next_single_experiment':'Frozen C versus frozen G_gpu on failure-enriched product-domain multi-pose RGB-D with independent held-out geometry.'};dump('FINAL_SYSTEM_DECISION_V1.json',final)
dump('BACK_REGION_READINESS_AUDIT_V1.json',{'status':'NOT_READY_FOR_BACK_SURFACE_ACCURACY','reason':'Only whole-body depth surfaces and a coarse topology torso map exist; no verified posterior/back partition or independent back ground truth.'})
dump('DATA_CONSUMPTION_RECEIPT_V1.json',{'status':'SYSTEM_VAL_AND_SYSTEM_SEALED_CONSUMED','system_val_subjects':['p000851','p000969'],'system_sealed_subjects':['p000838','p000891','p000893','p000931'],'final_deep_reserve_subjects':load('RGBD_SYSTEM_DATA_GOVERNANCE_V1.json')['groups']['FINAL_DEEP_RESERVE'],'final_deep_reserve_pixels_opened':False,'rules_changed_after_sealed':False})
dump('FAILURE_CASES_SYSTEM_V1.json',{'cheap_correction':{'out_of_range_fallback_frames':sum(r['correction_out_of_range'] for r in rows),'weak_subject':'p000838: C 34.51 mm vs G_exact 27.62 mm'},'selector':{'exact_gpu_disagreement_frames':sum(r['exact_choice']!=r['gpu_choice'] for r in rows),'remaining':'Both candidate meshes can fail together.'},'abstention':'No BAD80 positives in development/VAL; safety abstention unvalidated.','scope':'Small four-subject sealed; whole-body HuMMan with dataset ROI.'})
print(json.dumps(final,indent=2,ensure_ascii=False))
